### ISSUE TITLE
Multiple parallel coordinates (y-axis) on single plot

### ISSUE THREAD

**Issue by durack1** [UV-CDAT/vcs#11]
As mentioned by @jservonnat the following plot would certainly be a useful template to have handy when calculating and presenting metrics across a number of models or single model simulations - this will be useful for https://github.com/PCMDI/pcmdi_metrics/issues/421
![parallel_coordinates_with_r](https://cloud.githubusercontent.com/assets/3229632/18878814/e4ab76e2-8486-11e6-849d-a2d398d63f8c.png)

@doutriaux1 you're planning on working on this, correct?

**Comment by danlipsa** [comment]
@durack1 @doutriaux1 @aashish24 VTK has a parallel coordinates plot:

http://www.vtk.org/Wiki/VTK/Examples/Python/Infovis/ParallelCoordinatesExtraction

**Comment by durack1** [comment]
@danlipsa perfect - thanks for pointing this out!

**Comment by durack1** [comment]
@doutriaux1 transcribing your work here:
```python
import json
import vcs
J=self.loadJSON()
rms_xyt = J(statistic=["rms_xyt"],season=["ann"],region="global")(squeeze=1)
import vcsaddons
bg = True
#x=vcs.init(geometry=(800,600),bg=bg)
x=vcs.init()
gm = vcsaddons.createparallelcoordinates(x=x)
t = vcs.createtemplate()
to=x.createtextorientation("newxlbl")
to.angle=-45
to.halign="right"
to2=x.createtextorientation("newleg")
to2.height = 8
t.xlabel1.textorientation = to.name
t.legend.textorientation = to2.name
t.reset('x',0.05,0.77,t.data.x1,t.data.x2)
t.legend.x1 = t.data.x2 +.01
t.legend.x2 = .99
t.legend.y1 = t.data.y1
t.legend.y2 = t.data.y2
gm.plot(rms_xyt,template=t,bg=bg)
x.png("pcoords")
```
Yields:
![pcoords](https://cloud.githubusercontent.com/assets/3229632/19051571/4c87ade0-8968-11e6-8f7a-d419adbb66a4.png)

@jservonnat is there anything that should be tweaked in the default output here before this issue is closed?

**Comment by doutriaux1** [comment]
@durack1 I spoke with @jservonnat this morning we added capability to print units in between parenthesis next to variables, if the variable has a `units` attribute which happen to be a list of the units.
Everything else seems to be working as @jservonnat expects it to.
