### ISSUE TITLE
boxfill missing value does not respect opacity

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/vcs#121]
```python
import vcs
import cdms2

f=cdms2.open(vcs.sample_data+"/clt.nc")

s=f("clt")
x=vcs.init()
x.plot(s)
s2=cdms2.MV2.masked_greater(s,50.)
gm =x.createboxfill()
gm.missing=[50,50,50,50]
x.plot(s2,gm)

raw_input("press enteR")
```

gives: 
![crap](https://cloud.githubusercontent.com/assets/2781425/22228040/6e1d55c2-e183-11e6-9095-e1c5e5af22df.png)

**Comment by doutriaux1** [comment]
grey should be transparent

**Comment by durack1** [comment]
@doutriaux1 happy to test this out in my example case, so for isofill:
![bluemarble_siconc_satellite_view_daytimeview](https://cloud.githubusercontent.com/assets/3229632/22228191/69893110-e184-11e6-946e-f9d5bf517a60.png)
And for `boxfill`:
![bluemarble_siconc_satellite_view_daytimeview_boxfill](https://cloud.githubusercontent.com/assets/3229632/22228186/65d69508-e184-11e6-82e2-84f0b7ffdaca.png)
I'd also be curious about the `isofill` clipping along the Northern pole, this feature seems a weird artifact of the graphics method to me

**Comment by durack1** [comment]
@danlipsa it would be great to get your input on this, I was hoping to generate a correct figure (with the masking working correctly) by the end of this week

**Comment by sankhesh** [comment]
@doutriaux1 @durack1 Looking into this now

**Comment by durack1** [comment]
@sankhesh great, let me know when you have a branch to test..

**Comment by sankhesh** [comment]
@doutriaux1 @durack1 

PR #123 fixes the issue

Here is clt with `gm.missing = [50, 50, 50, 0]'

![121_boxfill_mask_opacity](https://cloud.githubusercontent.com/assets/936354/22350249/159ea5ee-e3e1-11e6-9dd6-725acfa24fc5.png)

and with `gm.missing = [50, 50, 50, 50]`

![121_boxfill_mask_opacity_50](https://cloud.githubusercontent.com/assets/936354/22350288/31d50640-e3e1-11e6-89f3-7a09341e37b3.png)

**Comment by doutriaux1** [comment]
awesome! thanks @sankhesh

**Comment by durack1** [comment]
@doutriaux1 great, once this is merged by @danlipsa will it be magically available through the `nightly` channel? I was hoping to get these figs done this week...

**Comment by durack1** [comment]
@danlipsa @doutriaux1 @sankhesh I'm also curious about the northern bound behaviour in the [`isofill` example above](https://github.com/UV-CDAT/vcs/issues/121#issuecomment-274657167). It seems that some boundary effect is impacting the `isofill` so that missing (or lower) values are found along the northern fringe, with `boxfill` this isn't an issue as there is no interpretation/interpolation of the data, it just plots cells as they are stored. I think the current `isofill` behaviour is wrong

**Comment by danlipsa** [comment]
@durack1 I don't really understand what is missing?

**Comment by danlipsa** [comment]
@durack1 Are these the black values along the northern bound?

**Comment by durack1** [comment]
@danlipsa exactly, so identical data yet you get the differences (the black values in `isofill` along the northern boundary) as per the screenshot below:
![isofilltopvsboxfillbottom](https://cloud.githubusercontent.com/assets/3229632/22353116/d05a16c4-e3d3-11e6-81b9-c7e43331dc9b.png)

**Comment by doutriaux1** [comment]
@danlipsa yes. It's odd, but I think it's the algorithm, not much we can do about it, high gradient around there

**Comment by danlipsa** [comment]
@durack1 Are the white values masked?

**Comment by durack1** [comment]
@doutriaux1 if you were to pad the boundary with the same value one pixel around the boundary (so obviously here it's 90N+), then you wouldn't get such an artifact.. And that is exactly what `boxfill` faithfully plots, `isofill` is attempting to pad with interpolated values

**Comment by durack1** [comment]
@danlipsa nope, the masked values (in `boxfill` lower panel) are the grey colour

**Comment by danlipsa** [comment]
@durack1 Can we have the nc file?

**Comment by durack1** [comment]
@danlipsa here you go, it's a single time slice.. I can provide the plotting script if you want that as well..
[siconc_input4MIPs_SSTsAndSeaIce_CMIP_PCMDI-AMIP-1-1-1_gn_187001.nc.zip](https://github.com/UV-CDAT/vcs/files/733810/siconc_input4MIPs_SSTsAndSeaIce_CMIP_PCMDI-AMIP-1-1-1_gn_187001.nc.zip)

**Comment by durack1** [comment]
@doutriaux1 it seems this change isn't [available through `nightly` on conda](https://anaconda.org/uvcdat/repo?label=nightly) the latest available build is 21st Jan 2017 (not 27/28th)

**Comment by durack1** [comment]
@sankhesh @danlipsa @doutriaux1 just to confirm, using the `vcx-nox 2017.2.22-py27_0 uvcdat/label/nightly` and `vtk-cdat-nox 7.1.0.2017.1.20-py27_0 uvcdat/label/nightly` yields the image below, which is exactly what I expected.. Thanks!
![bluemarble_siconc_satellite_view_daytimeview_boxfill](https://cloud.githubusercontent.com/assets/3229632/23235614/fdcec5cc-f90a-11e6-8cce-8f44bbf39129.png)
Compare the this `boxfill` image to the second image [above](https://github.com/UV-CDAT/vcs/issues/121#issuecomment-274657167)
