### ISSUE TITLE
x.show('crap') could return a sorted list of valid options

### ISSUE THREAD

**Issue by jypeter** [UV-CDAT/vcs#139]
Just a very minor request for improvement. It would be nice the displayed list for _Valid vcs elements_ below was **alphabetically sorted**. Just saying because I thought _colormap_ was not in there and then I discovered it was the next to last element!

Maybe there are other places that could use alphabetical sorting
```
>>> x = vcs.init()
>>> x.show('crap')
[...]
Exception: Error: 'crap' is not a valid vcs element
Valid vcs elements are: ['list', 'projection', 'texttable', 'textorientation', 'textcombined', 'line', 'marker', 'fillarea', 'font', 'fontNumber', 'boxfill', 'isofill', 'isoline', 'meshfill', '3d_scalar', '3d_dual_scalar', '3d_vector', 'template', 'taylordiagram', '1d', 'vector', 'yxvsx', 'xyvsy', 'xvsy', 'scatter', 'colormap', 'display']


```

**Comment by doutriaux1** [comment]
@jypeter see: https://github.com/UV-CDAT/vcs/pull/141

**Comment by jypeter** [comment]
Thanks!
I'll close this issue then. Though I don't know if it should be you or me closing it, or if you are supposed to wait till some tests pass

**Comment by doutriaux1** [comment]
@jypeter it will close when it's in master
