### ISSUE TITLE
vcs does not respect geometry on newer mac XCode 8.3

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/vcs#147]
bg=1 
geometry= {'width': 1200, 'height': 1091}

geometry not respected

```
Test file  : tests_png/test_vcs_1D_datawc_missing.png
Source file: uvcdat-testdata/baselines/vcs/test_vcs_1D_datawc_missing.png
Found Baselines:
- uvcdat-testdata/baselines/vcs/test_vcs_1D_datawc_missing.png
Comparing tests_png/test_vcs_1D_datawc_missing.png uvcdat-testdata/baselines/vcs/test_vcs_1D_datawc_missing.png ... ERROR: In /Users/doutriaux1/anaconda2/conda-bld/vtk-cdat_1484960149592/work/Imaging/Core/vtkImageDifference.cxx, line 555
vtkImageDifference (0x7f863fb22de0): ExecuteInformation: Input are not the same size.
 Input1 is: 0,599,0,545,0,0
 Input2 is: 0,1199,0,1090,0,0
```

**Comment by danlipsa** [comment]
We are working on it:
https://gitlab.kitware.com/vtk/vtk/merge_requests/2567#note_237976

**Comment by doutriaux1** [comment]
great! Because the graphics look really really bad on my new macbook pro! Any ETA on this?

**Comment by doutriaux1** [comment]
@danlipsa want me to build this sha on my mac and let you guys know?

**Comment by danlipsa** [comment]
@doutriaux1 No, as it does not work yet. A VTK contributor works on this, as he knows macs best. I think he tries to make VTK work both in hi res and low res mode with low res being default - that is the default apple behaviour.  We already have a solution to make it work only in hires.

**Comment by danlipsa** [comment]
@doutriaux1 The fix for this issue has just been merged into master.

**Comment by danlipsa** [comment]
This is the SHA: dbb7f8cec7c02c896d0d6a617d0f2207e0fd4bf1

**Comment by doutriaux1** [comment]
Awesome! Building it right now, will let you know!

**Comment by doutriaux1** [comment]
@danlipsa okay this is better, a few things are still borken
```python
import vcs
x=vcs.init()
x.plot([1,2,3])
```
opens the tiniest window ever

```python
z=vcs.init()
z.open()
z.plot(s)
z.clear()
z.close()
z.plot(s)
```
 leads to a picture with a red background
![red](https://cloud.githubusercontent.com/assets/2781425/24274588/79678e20-0fe6-11e7-8bbd-2cd3694fd3f0.png)

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 This sequence where you plot after close() does not work very well on linux either - I end up with a black background. I filed a new issue for it:
https://github.com/UV-CDAT/vcs/issues/154
I can take a look at this if we think is important.

**Comment by danlipsa** [comment]
@doutriaux1 Your first example with x.plot([1,2,3]) works fine on my mac book pro. Are you sure there isn't a configuration error. It does not make sense why certain windows would be OK and others would not.

**Comment by doutriaux1** [comment]
@danlipsa this on the newer mac with sierra and xcode 8.3. 
@danlipsa I can;t get your sha1 (or master) to compile on any mac Xcode 7 or 8

**Comment by doutriaux1** [comment]
example of what i get currently:
```
Compiling '/Users/doutriaux1/anaconda3/conda-bld/vtk-cdat_1490373529642/work/build/Wrapping/Python/twisted/words/protocols/jabber/sasl_mechanisms.py'...
Compiling '/Users/doutriaux1/anaconda3/conda-bld/vtk-cdat_1490373529642/work/build/Wrapping/Python/twisted/words/protocols/jabber/xmlstream.py'...
Compiling '/Users/doutriaux1/anaconda3/conda-bld/vtk-cdat_1490373529642/work/build/Wrapping/Python/twisted/words/protocols/jabber/xmpp_stringprep.py'...
***   File "/Users/doutriaux1/anaconda3/conda-bld/vtk-cdat_1490373529642/work/build/Wrapping/Python/twisted/words/protocols/jabber/xmpp_stringprep.py", line 136
    raise UnicodeError, "Invalid character %s" % repr(c)
                      ^
SyntaxError: invalid syntax
```

**Comment by doutriaux1** [comment]
ooops I see the issue here this  a python3

**Comment by doutriaux1** [comment]
back in a few

**Comment by danlipsa** [comment]
@doutriaux1 Is this still a bug, now that you built the new VTK?

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 There is still a problem with high res macs. You cannot have odd window dimensions if you open your app in high res (as all python apps are). Hopefully Sean McBride will fix this soon. See
https://gitlab.kitware.com/vtk/vtk/merge_requests/2567#note_237976

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 There seems to be an intrinsic problem with macs and windows with odd sizes (see the last commend on the link on gitlab) @doutriaux1 fixed this by resizing all baselines to even sizes.
