### ISSUE TITLE
Text location changes with `textAsPaths` setting

### ISSUE THREAD

**Issue by durack1** [UV-CDAT/vcs#150]
I have just generated two pdfs, one the default text settings and another with `textAsPaths=False`. The text alignment completely changes, which is not an expected output.

The output is as follows:
default 1.3Mb:
![test_4seasrms](https://cloud.githubusercontent.com/assets/3229632/24155845/26e9acb2-0e12-11e7-9c10-daf25237a11b.png)
`textAsPaths=False` 24.1Kb:
![test_4seasrmstextaspathfalse](https://cloud.githubusercontent.com/assets/3229632/24155884/38b4235a-0e12-11e7-9ab5-af38cced7c8d.png)
Versions of `VTK` and `vcs` are:
```
vcs-nox-2017.2.22-py27_0.json
vtk-cdat-nox-7.1.0.2017.1.20-py27_0.json
```

**Comment by danlipsa** [comment]
@durack1 This looks like it did not pick up the correct VTK. @doutriaux1 Can we tell what VTK is this using? Maybe we should include the SHA in the name of the package.

**Comment by durack1** [comment]
@danlipsa @doutriaux1 it seems that there are more up-to-date versions available:
https://anaconda.org/uvcdat/vtk-cdat/files
https://anaconda.org/uvcdat/vtk-cdat-nox/files
@danlipsa would you expect these more up-to-date versions will fix the problem?

**Comment by doutriaux1** [comment]
@durack1 please create a nightly conda (or use crunchy) and let me know.

**Comment by durack1** [comment]
@doutriaux1 I think the `nightly` channel needs an update, as I can't seem to get the latest (March) versions of the `vtk` or `vcs` packages:
```
durack1@oceanonly:[~]:[3873]> conda create -n uvcdatNightly -c conda-forge -c uvcdat/label/nightly -c uvcdat uvcdat
Fetching package metadata ...............                                                                          
Solving package specifications: .                                                                                  
Package plan for installation in environment /export/durack1/anaconda2/envs/uvcdatNightly:
The following NEW packages will be INSTALLED:
...
    uvcdat:                             2.8.0-0                      uvcdat
...
    vcs:                                2017.2.22-py27_0             uvcdat/label/nightly
    vcsaddons:                          2.8-py27_2                   uvcdat
...
    vtk-cdat:                           7.1.0.2.8-py27_2             uvcdat
```

**Comment by durack1** [comment]
@doutriaux1 I think the `nightly` channel needs an update, as I can't seem to get the latest (March) versions of the `vtk` or `vcs` packages:
```
durack1@oceanonly:[~]:[3873]> conda create -n uvcdatNightly -c conda-forge -c uvcdat/label/nightly -c uvcdat uvcdat
Fetching package metadata ...............                                                                          
Solving package specifications: .                                                                                  
Package plan for installation in environment /export/durack1/anaconda2/envs/uvcdatNightly:
The following NEW packages will be INSTALLED:
...
    uvcdat:                             2.8.0-0                      uvcdat
...
    vcs:                                2017.2.22-py27_0             uvcdat/label/nightly
    vcsaddons:                          2.8-py27_2                   uvcdat
...
    vtk-cdat:                           7.1.0.2.8-py27_2             uvcdat
```
It looks to me like we're missing the `linux-64` variants at [uvcdat/vtk-cdat](https://anaconda.org/uvcdat/vtk-cdat/files) (latest is 7.1.0.2017.2.23) and March updates for [uvcdat/vcs](https://anaconda.org/uvcdat/vcs/files) (latest is 2017.2.22)

@zshaheen is there something weird happening with the `linux-64` nightlies?

**Comment by durack1** [comment]
@doutriaux1 @danlipsa this looks fixed in the `vtk-cdat-nox-7.1.0.2017.3.14-py27_0`, there are very subtle text placement differences, but nothing that requires changes
`textAsPaths=True` (default) 1.3MB:
![test_4seasrms](https://cloud.githubusercontent.com/assets/3229632/24263932/e7e980c2-0fbb-11e7-8846-de8440108cc0.png)
`textAsPaths=False` 24.1KB:
![test_4seasrmstextaspathfalse](https://cloud.githubusercontent.com/assets/3229632/24263916/dbe84c5e-0fbb-11e7-8679-1208ec612d57.png)

So I'll close the issue

**Comment by danlipsa** [comment]
@durack1 The changes are because the fonts are different. vcs sets a font that is not a postscript standard font. With a standard font there are smaller differences (not sure why there are differences in that case - we'll have to investigate if we need to).

**Comment by durack1** [comment]
@danlipsa as a user, I actually prefer the second (`textAsPaths=False`) option, the spacing between the coloured box and the labels are better, and the file size is **far smaller**. Either way I think this is good, so I don't think there's anything else to look into on the "issue" (and I've closed this)
