### ISSUE TITLE
[Isoline] Difference in old VCS using Cairo and latest using VTK

### ISSUE THREAD

**Issue by sankhesh** [UV-CDAT/vcs#190]
The issue was first reported in https://github.com/UV-CDAT/uvcdat-testdata/pull/169#issuecomment-298678676 and https://github.com/UV-CDAT/uvcdat-testdata/pull/169#issuecomment-298678976

Old vcs | Latest vcs
:-------:|:----------:
![old vcs](https://cloud.githubusercontent.com/assets/2781425/25626762/66c96de4-2f15-11e7-8977-e99d9a1d9293.png) | ![new vcs](https://cloud.githubusercontent.com/assets/2781425/25626806/8cc757e0-2f15-11e7-9a99-463fe3f597d1.png)

As examined in https://github.com/UV-CDAT/uvcdat-testdata/pull/169#issuecomment-299308118, latest vcs can be used to generate similar plots by altering the line width.

linewidth = 0.5 | linewidth = 1.0 |
:-------------------:|:--------------------:
![isoline_width_0 5](https://cloud.githubusercontent.com/assets/936354/25724657/b7b774d6-30ea-11e7-8402-85dede361ce5.png) | ![isoline_width_1 0](https://cloud.githubusercontent.com/assets/936354/25724671/cb998390-30ea-11e7-9a4a-ca4ddc99458c.png)

Difference in text antialiasing pointed out in https://github.com/UV-CDAT/uvcdat-testdata/pull/169#issuecomment-299397714

**Comment by sankhesh** [comment]
Continuing from https://github.com/UV-CDAT/uvcdat-testdata/pull/169#issuecomment-299604315

@aashish24 Please see below, new images generated with `geometry=[1200, 1200]` and `antialiasing=8`.

linewidth = 0.5 | line width = 1.0
:--------------:|:---------------:
![isoline_width_0 5](https://cloud.githubusercontent.com/assets/936354/25769775/86af523a-31f0-11e7-95fd-c31ad4bcf48a.png) | ![isoline_width_1 0](https://cloud.githubusercontent.com/assets/936354/25769778/8d3dacb4-31f0-11e7-9f21-3eed126e6d2d.png)

**Comment by doutriaux1** [comment]
@sankhesh just tested this against 2.10 on a mac. (no nox) here's my code
```python
import cdat_info
import cdms2
import vcs

smpl_prfx = cdat_info.get_sampledata_path()
fnm = os.path.join(smpl_prfx,'clt.nc')
f=cdms2.open(fnm)
s=f("clt")
x=vcs.init()
x.plot(s,"default","isoline")
x.png("iso")
```
Plot looks great on screen, now when i do the png, I see another very small window pop up and render image which looks horrible and would explain the poor png

**Comment by doutriaux1** [comment]
Now doing 
```python
x.png("crp",width=1200,height=1090,units="pixels")
```
leads to a better quality png indeed, but I still see a window popup. png shouldn't do that. it's supposed to use the current window size and create an offscreen window.

**Comment by aashish24** [comment]
> leads to a better quality png indeed, but I still see a window popup. png shouldn't do that. it's supposed to use the current window size and create an offscreen window.

that is strange that there is a window popup. @sankhesh do you get a window to pop up as well? Why would it open another window just to save PNG is puzzling to me unless something is not set correctly.

**Comment by sankhesh** [comment]
> @sankhesh do you get a window to pop up as well? Why would it open another window just to save PNG is puzzling to me unless something is not set correctly.

I haven't tried the latest nox edition. I'll try it today and report back.

**Comment by doutriaux1** [comment]
@sankhesh this is regular not nox

**Comment by sankhesh** [comment]
> @sankhesh this is regular not nox

Oh I see. :face_with_thermometer: 
I **don't** see a window popup when I run the script with a regular build.

**Comment by danlipsa** [comment]
@doutriaux1 @sankhesh Maybe this has to do with the fact that png needs to resize a smaller window on the screen into bigger dimensions to save to the png.

**Comment by doutriaux1** [comment]
@danlipsa I doubt it because I have a window already opened on my screen so the png by defaulty should be of the same size.

**Comment by doutriaux1** [comment]
@sankhesh @danlipsa if you have a mac please try to install 2.10 as follow
```
conda create -n 2.10 -c ocnda-forge -c uvcdat uvcdat
```

Let me know.

**Comment by doutriaux1** [comment]
can you also try on Linux and let me know.

**Comment by danlipsa** [comment]
@doutriaux1 I get this on mac:
<pre>
(2.10) brasov:~ danlipsa$ python
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:05:08) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import cdat_info
>>> import cdms2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/danlipsa/anaconda/envs/2.10/lib/python2.7/site-packages/cdms2/__init__.py", line 19, in <module>
    from cdmsobj import CdArray, CdChar, CdByte, CdDouble, CdFloat, CdFromObject, CdInt, CdLong, CdScalar, CdShort, CdString
  File "/Users/danlipsa/anaconda/envs/2.10/lib/python2.7/site-packages/cdms2/cdmsobj.py", line 5, in <module>
    import cdmsNode
  File "/Users/danlipsa/anaconda/envs/2.10/lib/python2.7/site-packages/cdms2/cdmsNode.py", line 10, in <module>
    import cdtime
ImportError: dlopen(/Users/danlipsa/anaconda/envs/2.10/lib/python2.7/site-packages/cdtime.so, 2): Library not loaded: @rpath/libmfhdf.0.dylib
  Referenced from: /Users/danlipsa/anaconda/envs/2.10/lib/libnetcdf.11.dylib
  Reason: image not found
>>> 
</pre>

**Comment by doutriaux1** [comment]
what do you have for:
```
ls -l /Users/danlipsa/anaconda/envs/2.10/lib/libnet*
```

**Comment by danlipsa** [comment]
<pre>
(2.10) brasov:~ danlipsa$ ls -l /Users/danlipsa/anaconda/envs/2.10/lib/libnet*
-rwxr-xr-x  2 danlipsa  staff  1752380 Jul 20  2016 /Users/danlipsa/anaconda/envs/2.10/lib/libnetcdf.11.dylib
-rw-r--r--  2 danlipsa  staff  2208448 Jul 20  2016 /Users/danlipsa/anaconda/envs/2.10/lib/libnetcdf.a
lrwxr-xr-x  1 danlipsa  staff       18 May  8 13:01 /Users/danlipsa/anaconda/envs/2.10/lib/libnetcdf.dylib -> libnetcdf.11.dylib
-rwxr-xr-x  1 danlipsa  staff     1448 May  8 13:01 /Users/danlipsa/anaconda/envs/2.10/lib/libnetcdf.la
-rw-r--r--  1 danlipsa  staff      872 May  8 13:01 /Users/danlipsa/anaconda/envs/2.10/lib/libnetcdf.settings
(2.10) brasov:~ danlipsa$ 
</pre>

**Comment by doutriaux1** [comment]
so.... why can't it find it?

**Comment by doutriaux1** [comment]
what's in your root env?
```
ls -l /Users/danlipsa/anaconda/lib/libnet*
```

**Comment by danlipsa** [comment]
@doutriaux1 The problem was in the typo for the installation command you gave us 😄  (which I copy paste) It used ocnda-forge instead of conda-forge. 
Indeed, I get the same behavior you saw - the window is resized to be small and then it gets big again. My guess this is related to those pesky bgX bgY vcs settings. We should get rid of them once for all.

**Comment by doutriaux1** [comment]
agreed

**Comment by dnadeau4** [comment]
You probably got libnetcdf from `uvcdat` channel.   the HDF4 library does not link well (libmfhdf) with it.

**Comment by doutriaux1** [comment]
@dnadeau4 it was a typo

**Comment by danlipsa** [comment]
@sankhesh Are you going to look at this, or should I? Probably we should not release without this fix, isn't it @doutriaux1 ?

**Comment by doutriaux1** [comment]
well... It's annoying but you can still save at the resolution you need and I think it's mac only...

**Comment by danlipsa** [comment]
@doutriaux1 sounds good. Indeed, I think it is affecting only the default resolution, mac only.

**Comment by danlipsa** [comment]
@doutriaux1 There is a similar resizing going on on linux as well.

**Comment by doutriaux1** [comment]
doh... Is it a vtk issue then? Isnt' png creating an `offscreen` window?

**Comment by danlipsa** [comment]
@doutriaux1 I don't think so. I think the problem is that the window size is set based on the screen size but bgX and bgY still have the default values 800 x 600. png uses bgX and bgY rather than the window size, so it resizes the window to 800 x 600 saves the png and then resizes back to the old values.

**Comment by danlipsa** [comment]
@doutriaux1 I can look at this tomorrow if @sankhesh or @aashish24 are not already looking at it. Today I worked from home so I did not sync up with them.

**Comment by doutriaux1** [comment]
@danlipsa but do you see the popup as well on Linux? Because that is likely a vtk issue.

**Comment by danlipsa** [comment]
@doutriaux1 I don't really see a pop up on either platform. I see what I think is the resize on both platforms - but it happens very quickly so its not that clear.

**Comment by doutriaux1** [comment]
on my mac mymain window stays up and a small one pops-up and disappear.

**Comment by sankhesh** [comment]
@doutriaux1 I don't see any popup either. The main window remains open until the script runs and writes out the PNG file. It exits normally too.

**Comment by aashish24** [comment]
@sankhesh @doutriaux1 @danlipsa is it possible that VCS png writer creates a new window? Can we look at that code? I do not think VTK does not do that automatically. I have several examples of pure VTK code that I tried yesterday and didnot see any window.

**Comment by danlipsa** [comment]
@aashish24 @sankhesh I'll take a look at this. My guess is that this has to do with bgX bgY being different than the window size.

**Comment by aashish24** [comment]
@doutriaux1 can you verify if your plot (PNG's) also have anti-aliasing applied to it?
