### ISSUE TITLE
vcs.Gfb.rename() seems to destroy the object that it's renaming

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/vcs#2]
submitted by @embrown at:
https://github.com/UV-CDAT/uvcdat/issues/2116

**Comment by embrown** [comment]
@doutriaux1 I think I solved this problem. Want me to make a test and submit the new rename() code with a PR?

**Comment by embrown** [comment]
@doutriaux1 PR submitted. Let me know if there's anything I need to change.
