### ISSUE TITLE
Release 2.10.1 with 1D plot slowdown fix

### ISSUE THREAD

**Issue by zshaheen** [UV-CDAT/vcs#202]
It would be really nice if there could be a 2.10.1 release of vcs, which includes the 1D plot speedup.

We (@chengzhuzhang and I) are releasing some software soon that uses vcs and a 2.10.1 release would make it painless for users to install vcs via Anaconda. In addition, the consensus is that the vcs plots look better than the alternatives (i.e. matplotlib), so a release of vcs with the 1D plot fix would be a good way to sell vcs.

In general, having more often releases of vcs would be good, because other software that uses vcs can have the latest feature/bug fixes. Or just have nightly Anaconda releases, but hopefully no one will delete them.

Thanks!

**Comment by durack1** [comment]
@zshaheen good call!

**Comment by doutriaux1** [comment]
@zshaheen that's what the nightlies are really for. I'm planning on a patch release in late July.

**Comment by doutriaux1** [comment]
@zshaheen but if you want to go through all the pains of a release more often I'd be glad to hand over the job to you (tagging multiple repo, creating metapackage, release notes, annoucement, zenodo, README, etc...)

**Comment by zshaheen** [comment]
@doutriaux1 Should we then begin releasing nightlies for vcs? 

Because that's cool, but someone deleted the vtk-cdat-nox >=7.1.0.2017.3 nightlies and that messed stuff up for users who were on 2.8 and who wanted to install older versions which used 2.8. As long as the nightlies don't go away, we're good with that.

**Comment by doutriaux1** [comment]
@zshaheen it's stuck in a PR that doesn't pass fixing it today.

**Comment by doutriaux1** [comment]
2.12 finally here!
