### ISSUE TITLE
remove bgX, bgY

### ISSUE THREAD

**Issue by danlipsa** [UV-CDAT/vcs#209]
bgX and bgY have a complex logic to decide when and how are they set and when they should be used
for OnScreen graphics or OffScreen Mesa.

For instance, the following script, run with OSMesa, does not set the dimensions for png properly. If you un-comment  bgX and bgY statements, png dimensions are set as expected: 1200x800.

We should remove them and always use the window dimensions, or the dimensions passed to the png function.

<pre>
import vcs
import time
import numpy
import cdms2

f=cdms2.open(vcs.sample_data+"/clt.nc")
s=f("clt")
x=vcs.init()
x.open()
x.geometry(1200,800)
# x.bgX = 1200
# x.bgY = 800

gmtype = "isofill"
start = time.time()
gm = vcs.creategraphicsmethod(gmtype)
x.plot(gm,s)
end = time.time()
x.png("test.png")
elapsed = end - start
x.clear()
x.removeobject(gm)
print elapsed
</pre>

**Comment by doutriaux1** [comment]
I like the idea.
