### ISSUE TITLE
on screen mac window size is half what it should be

### ISSUE THREAD

**Issue by danlipsa** [UV-CDAT/vcs#212]
From @doutriaux1 
No it’s not related to bgX/bgY on my mac, both ipython and python lead to a tiny window:
>>> x=vcs.init()
>>> x.geometry(1200,600)
>>> x.open()
 
subsequent calls to landscape/portrait/geometry do not alter size. (portrait/landscape do switch the orientation though)

**Comment by danlipsa** [comment]
@doutriaux1 It turns out this is correct. VTK uses hardware pixels rather than logical pixels. So when you ask VTK for 1200 x 600 pixels, it will give you that many hardware pixels which results in 600 x 300 logical pixels (as reported by mac os). This way, when you save a png you end-up with a png of size 1200 x 600. 

If we want the window to have a certain size on the screen we should add a unit the way we have for png.

**Comment by doutriaux1** [comment]
@danlipsa ok that makes sense. It's annoying though... Should we add some if tests for mac? And assume the user is passing logical pixel? that means adding the "hardware_pixel" option to png, and making sure it knows on mac that the size is in hardware pixels. Or is there an option in VTK to obtain the logical pixels size?

**Comment by danlipsa** [comment]
@doutriaux1 vtkCocoaRenderWindow knows about logical pixels (points) but we might need to add a function to access that. I am not a big fan of how Apple has hidden the increased pixel density. 

I would prefer to add on option to create a window based on size (such as inches or cm). This way it would be clearer what the user wants and it would be easy to measure on the screen.

As an option, we can create the window using the logical pixels (points) to keep compatibility  with how mac does things. Pngs will be saved at 4 times the number of pixels though (2 in each direction). But I prefer the first option.
