### ISSUE TITLE
taylordiagram should be able to draw ids only in legend not on plot

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/vcs#222]

**Comment by doutriaux1** [comment]
@lee1043 @chengzhuzhang I'm thinking of adding an option to control this
Two possibilities
```python
import vcs
td = vcs.createtaylordiagram()
td.idsOnLegendOnly = True  # do not plot ids on plot, only in legend
```
or
```python
import vcs
td = vcs.createtaylordiagram()
td.addMarker(id="My Id", plot_id=False)
```

The second one gets you more control, you can turn on/off individual ids

Personally I prefer option 2

The could also have 1 AND 2 but then we need to decide which one overrides the other. I'd say option 2 overrides option 1.

Please comment

**Comment by doutriaux1** [comment]
could also be:
```python
import vcs
td = vcs.createtaylordiagram()
td.addMarker(id="My Id", id_on_legend_only=True)
```

or 
```python
import vcs
td = vcs.createtaylordiagram()
td.plotIds = False  # do not plot ids on plot, only in legend
```

**Comment by lee1043** [comment]
@doutriaux1 It would be nice if user can 1) remove all IDs on the plot, or 2) show only few selected IDs on the plot. I guess the option 2 works for this, correct?

**Comment by doutriaux1** [comment]
yes you're correct @lee1043 the . ore I think about it the more I think we need 1 and 2

**Comment by chengzhuzhang** [comment]
Option 2 seems better to me.

When I use td.addMarker, if I don't set "id = ", the id name won't show up in the plot. It works the same as option 2, right?
