### ISSUE TITLE
resize does not work correctly

### ISSUE THREAD

**Issue by danlipsa** [UV-CDAT/vcs#228]
The following script does not work correctly in 2.10 or nightly. It works fine in 2.8. I remember this is one thing I fixed about a year ago when working on vcs.js. It seems vcs regressed in this regard.

x.interact() does not work well either. After a few resizes that do not resize properly, the plot crashes.

<pre>
import vcs
import cdms2

f=cdms2.open('coads_climatology.nc')
vx=f('UWND')
vy=f('VWND')

x=vcs.init()

x.plot(vx, vy, 'default', 'vector', 'default', ratio="autot")
# x.interact()
x.png('vector.png')
x.geometry(800,600)
x.png('vector-after.png')
</pre>
vector.png
![vector](https://user-images.githubusercontent.com/6180727/28228329-0b22b934-68ac-11e7-8e0c-7e97e9401e6c.png)
vector-after.png
![vector-after](https://user-images.githubusercontent.com/6180727/28228328-0b22c370-68ac-11e7-8496-1788932425be.png)

**Comment by danlipsa** [comment]
Note, this is with the on screen hardware driver. With mesa, the same script crashes.

**Comment by doutriaux1** [comment]
@danlipsa it probably does not matter here, but one is not supposed to called the backend directly

**Comment by doutriaux1** [comment]
@danlipsa does:
```python
x.geometry(800,660)
```
works better?

**Comment by danlipsa** [comment]
@doutriaux1 No, the same thing.

**Comment by danlipsa** [comment]
@doutriaux1 Also, tests/test_vcs_png_window_resize.py fails with an on-screen driver. Maybe we should consider bringing back the buildbot with an onscreen driver.

**Comment by doutriaux1** [comment]
@danlipsa the issue is that most test will fail because of baseline glitches. I think it's overkill to maintain 3 or 4 baselines for on/offscreen. But we could use the `attributes` idea that I started to implement a bit (https://github.com/UV-CDAT/vcs/blob/master/tests/test_vcs_vectors_and_streamlines_robinson.py#L44 , https://github.com/UV-CDAT/vcs/blob/master/run_tests.py#L144-L145 and https://github.com/UV-CDAT/vcs/blob/master/tests/vtk_ui/vtk_ui_test.py#L134 ) to mark the ones that should be ran onscreen and/or the ones that do not need graphics output at all.

**Comment by danlipsa** [comment]
@doutriaux1 Indeed, we could run only a subset of the tests. It would be nice to run them automatically though, for every commit.

**Comment by doutriaux1** [comment]
@danlipsa ok then https://github.com/UV-CDAT/ci-bots seems like the perfect candidate. I will see if I can revive/setup macbot1 and macbot2.

**Comment by doutriaux1** [comment]
@danlipsa any ubuntu/linux machine Kitware could dedicate to this?

**Comment by danlipsa** [comment]
@doutriaux1 What is the difference between ci-bot and buildbot + @sankhesh changes? I remember we talked about doing testing on one of our buildbots before we started using travis ci / circle ci. @aashish24 @sankhesh ?

**Comment by doutriaux1** [comment]
I don't know about buildbots anymore, it has never quite worked for us behind the firewall.
