### ISSUE TITLE
vcs.removeobject doex NOT error exit if trying to remove a non vcs object

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/vcs#234]
but rather prints to the screen

```python
In [1]: import EzTemplate

In [2]: M=EzTemplate.Multi(rows=3,columns=3)

In [3]: M.get()
Out[3]: <vcs.template.P at 0x7f910a927bb0>

In [4]: vcs.removeobject(M)
Out[4]: 'This is not a template, graphics method, or secondary method object.'
```

Should we error exit?

reported by @lee1043 
please @durack1 and @danlipsa let me know what you think

**Comment by durack1** [comment]
@doutriaux1 I would vote an "error" message yields and error response - so 👍  your suggestion

**Comment by durack1** [comment]
@doutriaux1 I'd actually be interested to know what methods are available in `vcs.` it might be a good time to remove a bunch of redundant functions..?

**Comment by jypeter** [comment]
I did not even know about this function... Would you get the same result with a standard **del(M)**?

When I want to explicitly delete a big numpy or MV2 array (before the end of a script), I just use **del(my_bulky_array)** and I don't need a _cdms2.removeobject_. I hope using _del_ works!

**Comment by doutriaux1** [comment]
@jypeter I am 99% certain del(vcsobj) won't clean it from vcs memory.

**Comment by jypeter** [comment]
Oh, OK.

What about using `del `on numpy arrays or cdms2 objects (sorry if this is not related to this thread)? I have sometimes told people to use that to remove temporary/intermediate data when they had memory issues, but I have never checked if it actually worked

**Comment by doutriaux1** [comment]
yes no issue with numpy arrays.
