### ISSUE TITLE
3d_scalar seg faults on mac

### ISSUE THREAD

**Issue by danlipsa** [UV-CDAT/vcs#245]
The following script seg faults on my mac. It works on linux. Upgrading to opengl2 might fix this. @doutriaux1 @aashish24 Do we test 3D plots?

```python
import vcs
import cdms2
f=cdms2.open("http://test.opendap.org/dap/data/nc/coads_climatology.nc")
x=vcs.init()
s=f["AIRT"]
gm=x.get3d_scalar()
x.plot(s,gm)
```

**Comment by danlipsa** [comment]
@doutriaux1 Indeed, on linux I have 2.10 on mac I have 2.12.

**Comment by dnadeau4** [comment]
I just pushed a change on cdtime to make sure I deference the pointer correctly.
https://github.com/UV-CDAT/cdtime/commit/1111ec47f943b30f5125fa9d35a77c4d9fc8a3be

**Comment by doutriaux1** [comment]
@dnadeau4 that fixes it on the mac! Thanks!

**Comment by danlipsa** [comment]
@doutriaux1 Is this on conda nightly?

**Comment by doutriaux1** [comment]
@danlipsa it is a py3 issue, reverted to py2 only (like v2.10) it's on conda-forge queue should be in overnight

**Comment by danlipsa** [comment]
Thanks @doutriaux1 @dnadeau4 I did a python setup.py install and that fixed it.

**Comment by doutriaux1** [comment]
@danlipsa linux cdtime is now on conda-forge, expecting mac version around midnight PDT tonight

**Comment by doutriaux1** [comment]
mac still in conda-forge queue... 17hours... unbelievable...

**Comment by danlipsa** [comment]
@doutriaux1 No worries ... I already installed the correct version manually.
I wonder if there is any way to trigger a vcs rounds of tests each time we change one of its conda packages. This way, we'll know if one of the packages broke something.

**Comment by doutriaux1** [comment]
@danlipsa in this case that wouldn't help us because the test suite passed against cdtime. I did manually test vcs on both mac and linux when I put the py3 code in, and we did find some breakage already then. One way to achieve this would be to run vcs, cdms, etc.. as part of cdtime test suite, but it would take a long time...
