### ISSUE TITLE
fillarea creates black area

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/vcs#254]
```python
import vcs
x=vcs.init()
o = vcs.createfillarea()
xs = [-70.0, -66.0, -62.0, -58.0, -54.0, -50.0, -46.0, -46.0, -50.0, -54.0, -58.0, -62.0, -66.0, -70.0]
ys = [97.40004179212772, 99.24051369561087, 99.64501380920407, 99.50791666242807, 99.25809764862053, 98.72724999321828, 97.86243057250978, 66.1760279867384, 78.08891693751016, 84.6064443588257, 75.83586128552756, 54.88270839055378, 33.08841943740845, 32.207757042513954]
o.x = xs
o.y = ys
o.worldcoordinate = [-70,-35,30,100]
x.plot(o)
```
generates:
![badfill](https://user-images.githubusercontent.com/2781425/30348572-bc410a76-97c4-11e7-96e9-b2c6b2f51c64.png)

**Comment by doutriaux1** [comment]
why is there black?

**Comment by doutriaux1** [comment]
using a line produce the correct result:
![okline](https://user-images.githubusercontent.com/2781425/30348651-fcfc0bba-97c4-11e7-9aee-ad1a7e431dc9.png)

**Comment by durack1** [comment]
@doutriaux1 even though it's wrong, the [top image kinda looks like 3D](https://github.com/UV-CDAT/vcs/issues/254#issue-257184863).. Kinda cool

**Comment by jypeter** [comment]
Not much 3D. I have tried to shake my screen to see if the shadow was moving, but no result :p

**Comment by doutriaux1** [comment]
@danlipsa @aashish24 any progress on this? I ran into this again last week.

**Comment by doutriaux1** [comment]
went back all the way to commit: 3c70e0f685d3ec886c52e37aece284a5aa791143 bug was here.

At this commit vtk api changed and I can't get a working vtk

**Comment by doutriaux1** [comment]
@danlipsa @aashish24 I can reproduce this in pure vtk
```python
import vtk

xs = [-70.0, -66.0, -62.0, -58.0, -54.0, -50.0, -46.0, -46.0, -50.0, -54.0, -58.0, -62.0, -66.0, -70.0]
ys = [97.40004179212772, 99.24051369561087, 99.64501380920407, 99.50791666242807, 99.25809764862053, 98.72724999321828, 97.86243057250978, 66.1760279867384, 78.08891693751016, 84.6064443588257, 75.83586128552756, 54.88270839055378, 33.08841943740845, 32.207757042513954]

N = len(xs)
pts = vtk.vtkPoints()
for i in range(N):
    pts.InsertNextPoint(xs[i],ys[i],0.)

polygon = vtk.vtkPolygon()
polygon.GetPointIds().SetNumberOfIds(N)
for i in range(N):
    polygon.GetPointIds().SetId(i,i)

polygons = vtk.vtkCellArray()
polygons.InsertNextCell(polygon)
polygonPolyData = vtk.vtkPolyData()
polygonPolyData.SetPoints(pts)
polygonPolyData.SetPolys(polygons)

mapper = vtk.vtkPolyDataMapper()
mapper.SetInputData(polygonPolyData)

actor = vtk.vtkActor()
actor.SetMapper(mapper)

renderer = vtk.vtkRenderer()
renWin = vtk.vtkRenderWindow()

renWin.AddRenderer(renderer)
renIter = vtk.vtkRenderWindowInteractor()
renIter.SetRenderWindow(renWin)

renderer.AddActor(actor)
renderer.SetBackground(.5,.3,.31)
renWin.Render()
renIter.Start()
```

Should I submit a bug on VTK site?

**Comment by doutriaux1** [comment]
reported there: https://gitlab.kitware.com/vtk/vtk/issues/17141

**Comment by danlipsa** [comment]
@doutriaux1 You cannot fill concave polygons in OpenGL. You'll have to split them in triangles.
https://www.opengl.org/discussion_boards/showthread.php/153256-How-draw-fill-non-convex-polygon-in-OpenGl
Do we need to add this functionality to VCS?

**Comment by doutriaux1** [comment]
yes! definitely! I ran into this twice in two weeks now. I'll take a closer look at your post and see if we can "hack" this.

**Comment by doutriaux1** [comment]
@danlipsa actually it was easy to make it work:
```python
import vcs
x=vcs.init(bg=True,geometry=(300,300))
f = vcs.createfillarea()
xs = [-70.0, -66.0, -62.0, -58.0, -54.0, -50.0, -46.0, -46.0, -50.0, -54.0, -58.0, -62.0, -66.0, -70.0]
ys = [97.40004179212772, 99.24051369561087, 99.64501380920407, 99.50791666242807, 99.25809764862053, 98.72724999321828, 97.86243057250978, 66.1760279867384, 78.08891693751016, 84.6064443588257, 75.83586128552756, 54.88270839055378, 33.08841943740845, 32.207757042513954]
f.x = xs[::-1]
f.y = ys[::-1]
f.worldcoordinate = [-70,-35,30,100]
x.plot(f)
```

simply revert the vertices. I'll implement a patch soon. It's clockwise vs counterclockwise issue

**Comment by danlipsa** [comment]
@doutriaux1 Great.

**Comment by doutriaux1** [comment]
hum... that wasn't it. It was enough for this example but not enough for my full blown example. @danlipsa any good/fast functions I can use in VTK to triangulate the polygon first?

**Comment by jypeter** [comment]
@doutriaux1 Can you use [scipy.spatial.Delaunay](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.spatial.Delaunay.html) ?

**Comment by doutriaux1** [comment]
@jypeter I will try it, but I would like to avoid making scipy a dependency of vcs.

**Comment by danlipsa** [comment]
@doutriaux1 Try this:
https://www.vtk.org/doc/nightly/html/classvtkContourTriangulator.html
I don't think Delaunay works as the input there are points not a polygon. But VTK has that as well.

**Comment by doutriaux1** [comment]
@danlipsa @aashish24 I got a barebone example of what essentially vcs is doing for a fillarea but in pure VTK

Not sure how to use the vtkContoureTraingulate though any hint welcome:
```python
import vtk
pts = vtk.vtkPoints()
polygons = vtk.vtkCellArray()
polygonPolyData = vtk.vtkPolyData()
polygonPolyData.SetPoints(pts)
polygonPolyData.SetPolys(polygons)
colors = vtk.vtkUnsignedCharArray()
colors.SetNumberOfComponents(4)
colors.SetNumberOfTuples(n)
colors.SetName("Colors")
polygonPolyData.GetCellData().SetScalars(colors)

xs = [0,10,10,5,0,0]
ys = [0,0,6,3,6,0]

x = numpy.array(xs)
x /= x.max()
y = numpy.array(ys)
y /= y.max()
x = x.tolist()
y = y.tolist()

points, polys, pd, color_arr = pts, polygons, polygonPolyData, colors
N = max(len(x), len(y))
polygon = vtk.vtkPolygon()
# Add current polygon
pid = polygon.GetPointIds()
pid.SetNumberOfIds(N)
for j in range(N):
    pid.SetId(j, points.InsertNextPoint(x[j], y[j], 0.))
cellId = polys.InsertNextCell(polygon)
color = [ 255,0,0,255]
color_arr.SetTypedTuple(cellId, color)
polygonPolyData.SetPoints(pts)
tr = vtk.vtkContourTriangulator()
#o = tr.TriangulatePolygon(pid,points,polys.GetCell())
m = vtk.vtkPolyDataMapper()
m.SetInputData(polygonPolyData)
a = vtk.vtkActor()
a.SetMapper(m)
    
renWin = vtk.vtkRenderWindow()
renWin.SetSize(600,600)
ren = vtk.vtkRenderer()
ren.AddActor(a)
renWin.AddRenderer(ren)
i = vtk.vtkRenderWindowInteractor()
renWin.SetInteractor(i)
i.Initialize()
#i.SetRenderWindow(renWin)
renWin.Render()
i.Start()
```

**Comment by doutriaux1** [comment]
@aashish24 @danlipsa @scottwittenburg who at Kitware can take a look?

**Comment by doutriaux1** [comment]
@danlipsa you think OpenGL2,.0 will fix this?

**Comment by danlipsa** [comment]
@doutriaux1 I was just thinking to fix this. I had to do something similar in my other project. It should work with what we have.

**Comment by doutriaux1** [comment]
That would be fantastic!
