### ISSUE TITLE
regression regarding colormaps color range of (16,240)? ￼

### ISSUE THREAD

**Issue by danlipsa** [UV-CDAT/vcs#259]
I run the nightly uvcdat tests on my machine and I get some failures:

test_vcs_basic_vectors_45_2_amplitude.png
test_vcs_click_info_boxfill.png
test_vcs_legend_boxfill_horizontal_ext1_y_ext2_y.png

@doutriaux1 Do you know anything about this?
Not sure if this affects the release.

![test_vcs_click_info_boxfill](https://user-images.githubusercontent.com/6180727/30554847-de775fb0-9c73-11e7-8eea-a06d1dbcfccf.png)
![test_vcs_basic_vectors_45_2_amplitude](https://user-images.githubusercontent.com/6180727/30554863-e46f3d5c-9c73-11e7-84b2-81c61ba513b4.png)
![test_vcs_legend_boxfill_horizontal_ext1_y_ext2_y](https://user-images.githubusercontent.com/6180727/30554871-ec1a7ada-9c73-11e7-9e2a-b454c274203b.png)

**Comment by doutriaux1** [comment]
@danlipsa try re-running with -f and see if they pass
if they do, that means this multiprocess memory corruption thing is all over the place.

**Comment by doutriaux1** [comment]
```
python run_tests.py -v2 -H -f
```
reruns only the ones that failed before

**Comment by danlipsa** [comment]
@doutriaux1 Does not seem so:

(nightly-20170918) [~/projects/vcs/src (context2d $%)]$ nosetests -s tests/test_vcs_basic_vectors.py
45 72
Test file  : tests_png/test_vcs_basic_vectors_-180.png
Source file: uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_-180.png
Found Baselines:
- uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_-180.png
Comparing tests_png/test_vcs_basic_vectors_-180.png uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_-180.png ... diff=0.000000, New best!Baseline 'uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_-180.png' is the best match with a difference of 0.000000.
Deleting test image 'tests_png/test_vcs_basic_vectors_-180.png'...
45 72
Test file  : tests_png/test_vcs_basic_vectors_-135.png
Source file: uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_-135.png
Found Baselines:
- uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_-135.png
Comparing tests_png/test_vcs_basic_vectors_-135.png uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_-135.png ... diff=0.000000, New best!Baseline 'uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_-135.png' is the best match with a difference of 0.000000.
Deleting test image 'tests_png/test_vcs_basic_vectors_-135.png'...
45 72
Test file  : tests_png/test_vcs_basic_vectors_-90.png
Source file: uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_-90.png
Found Baselines:
- uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_-90.png
Comparing tests_png/test_vcs_basic_vectors_-90.png uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_-90.png ... diff=0.000000, New best!Baseline 'uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_-90.png' is the best match with a difference of 0.000000.
Deleting test image 'tests_png/test_vcs_basic_vectors_-90.png'...
45 72
Test file  : tests_png/test_vcs_basic_vectors_-45.png
Source file: uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_-45.png
Found Baselines:
- uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_-45.png
Comparing tests_png/test_vcs_basic_vectors_-45.png uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_-45.png ... diff=0.000000, New best!Baseline 'uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_-45.png' is the best match with a difference of 0.000000.
Deleting test image 'tests_png/test_vcs_basic_vectors_-45.png'...
45 72
Test file  : tests_png/test_vcs_basic_vectors_0.png
Source file: uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_0.png
Found Baselines:
- uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_0.png
Comparing tests_png/test_vcs_basic_vectors_0.png uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_0.png ... diff=0.000000, New best!Baseline 'uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_0.png' is the best match with a difference of 0.000000.
Deleting test image 'tests_png/test_vcs_basic_vectors_0.png'...
45 72
Test file  : tests_png/test_vcs_basic_vectors_45.png
Source file: uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_45.png
Found Baselines:
- uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_45.png
- uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_45_0.5.png
- uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_45_2.png
- uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_45_2_amplitude.png
Comparing tests_png/test_vcs_basic_vectors_45.png uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_45.png ... diff=0.000000, New best!Baseline 'uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_45.png' is the best match with a difference of 0.000000.
Deleting test image 'tests_png/test_vcs_basic_vectors_45.png'...
45 72
Test file  : tests_png/test_vcs_basic_vectors_90.png
Source file: uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_90.png
Found Baselines:
- uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_90.png
Comparing tests_png/test_vcs_basic_vectors_90.png uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_90.png ... diff=0.000000, New best!Baseline 'uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_90.png' is the best match with a difference of 0.000000.
Deleting test image 'tests_png/test_vcs_basic_vectors_90.png'...
45 72
Test file  : tests_png/test_vcs_basic_vectors_135.png
Source file: uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_135.png
Found Baselines:
- uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_135.png
Comparing tests_png/test_vcs_basic_vectors_135.png uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_135.png ... diff=0.000000, New best!Baseline 'uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_135.png' is the best match with a difference of 0.000000.
Deleting test image 'tests_png/test_vcs_basic_vectors_135.png'...
45 72
Test file  : tests_png/test_vcs_basic_vectors_45_0.5.png
Source file: uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_45_0.5.png
Found Baselines:
- uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_45_0.5.png
Comparing tests_png/test_vcs_basic_vectors_45_0.5.png uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_45_0.5.png ... diff=0.000000, New best!Baseline 'uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_45_0.5.png' is the best match with a difference of 0.000000.
Deleting test image 'tests_png/test_vcs_basic_vectors_45_0.5.png'...
45 72
Test file  : tests_png/test_vcs_basic_vectors_45_2.png
Source file: uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_45_2.png
Found Baselines:
- uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_45_2.png
- uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_45_2_amplitude.png
Comparing tests_png/test_vcs_basic_vectors_45_2.png uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_45_2.png ... diff=0.000000, New best!Baseline 'uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_45_2.png' is the best match with a difference of 0.000000.
Deleting test image 'tests_png/test_vcs_basic_vectors_45_2.png'...
45 72
Test file  : tests_png/test_vcs_basic_vectors_45_2_amplitude.png
Source file: uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_45_2_amplitude.png
Found Baselines:
- uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_45_2_amplitude.png
Comparing tests_png/test_vcs_basic_vectors_45_2_amplitude.png uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_45_2_amplitude.png ... diff=8103.349020, New best!
All baselines failed! Lowest error (8103.349020) exceeds threshold (10.000000).
Saving image diff at tests_png/test_vcs_basic_vectors_45_2_amplitude_diff.png
<DartMeasurement name="ImageError" type="numeric/double">8103.349020</DartMeasurement>
<DartMeasurementFile name="TestImage" type="image/png">/home/danlipsa/projects/vcs/src/tests_png/test_vcs_basic_vectors_45_2_amplitude.png</DartMeasurementFile>
<DartMeasurementFile name="DifferenceImage" type="image/png">/home/danlipsa/projects/vcs/src/tests_png/test_vcs_basic_vectors_45_2_amplitude_diff.png</DartMeasurementFile>
<DartMeasurementFile name="ValidImage" type="image/png">/home/danlipsa/projects/vcs/src/uvcdat-testdata/baselines/vcs/test_vcs_basic_vectors_45_2_amplitude.png</DartMeasurementFile>
F
======================================================================
FAIL: testBasicVectors (test_vcs_basic_vectors.TestVCSBasicVectors)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/danlipsa/projects/vcs/src/tests/test_vcs_basic_vectors.py", line 68, in testBasicVectors
    self.basicVector(scale=2.,angle=45,amplitude=True)
  File "/home/danlipsa/projects/vcs/src/tests/test_vcs_basic_vectors.py", line 62, in basicVector
    self.checkImage(fnm)
  File "/home/danlipsa/projects/vcs/src/tests/basevcstest.py", line 63, in checkImage
    self.assertEqual(ret,0)
AssertionError: -1 != 0

----------------------------------------------------------------------
Ran 1 test in 6.711s

FAILED (failures=1)

**Comment by doutriaux1** [comment]
hum.. With mesa? Let me try. On my mac here.

**Comment by doutriaux1** [comment]
passes for me. Did you install nose inside your conda env? i had issue before if I was using not actually in the env.

**Comment by danlipsa** [comment]
Initially I run this with hardware driver, but osmesa behaves the same. I did install nose in my conda env. Very strange. I'll take a close look ...

**Comment by danlipsa** [comment]
@doutriaux1 This is what I get for the rainbow color map. Should this be white and black?
This is what the baseline shows:
https://github.com/UV-CDAT/uvcdat-testdata/blob/master/baselines/vcs/test_vcs_basic_vectors_45_2_amplitude.png


>>> import vcs
>>> print vcs.elements["colormap"]["rainbow"].getcolorcell(240)
[84, 88, 9, 100]
>>> print vcs.elements["colormap"]["rainbow"].getcolorcell(241)
[85, 88, 9, 100]

**Comment by danlipsa** [comment]
@doutriaux1 This works correctly on mac. I'll install a fresh nightly on my linux.
>>> import vcs
>>> print vcs.elements["colormap"]["rainbow"].getcolorcell(240)
[100, 100, 100, 100.0]
>>> print vcs.elements["colormap"]["rainbow"].getcolorcell(241)
[0, 0, 0, 100.0]

**Comment by danlipsa** [comment]
It works as I said in my first posting for fresh nightly Linux.

**Comment by doutriaux1** [comment]
really? Ok let me try it as well then.

**Comment by doutriaux1** [comment]
works for me!

**Comment by doutriaux1** [comment]
@danlipsa are you sure your "uvcdat-testdata" directory is up to date?

**Comment by doutriaux1** [comment]
are you using the correct nose?
```
doutriaux1@crunchy:[vcs]:[master]:[16980]> which nosetests 
~/miniconda2/envs/dev-nox/bin/nosetests
```

**Comment by danlipsa** [comment]
@doutriaux1 I am only looking at vcs.elements['colormap']['rainbow'] after vcs.init(). Here is the init sequence on mac. the printout is after Cp.__init__ Something funky does go on.
('default', ', ', 'default')
('blue2darkred', ', ', 'default')
('bl_to_darkred', ', ', 'default')
('classic', ', ', 'default')
('viridis', ', ', 'default')
('white2blue', ', ', 'default')
('white_to_blue', ', ', 'default')
('rainbownogreen', ', ', 'default')
('rainbow_no_grn', ', ', 'default')
('magma', ', ', 'default')
('rainbow', ', ', 'default')
[84, 88, 9, 100]
('blue2orange2red', ', ', 'default')
[100, 100, 100, 100.0]
('blue_to_orgred', ', ', 'default')
[100, 100, 100, 100.0]
('categorical', ', ', 'default')
[100, 100, 100, 100.0]
('sequential', ', ', 'default')
[100, 100, 100, 100.0]
('blue2green', ', ', 'default')
[100, 100, 100, 100.0]
('blue_to_grn', ', ', 'default')
[100, 100, 100, 100.0]
('NCAR', ', ', 'default')
[100, 100, 100, 100.0]
('inferno', ', ', 'default')
[100, 100, 100, 100.0]
('plasma', ', ', 'default')
[100, 100, 100, 100.0]
('white2red', ', ', 'default')
[100, 100, 100, 100.0]
('white_to_red', ', ', 'default')
[100, 100, 100, 100.0]
('white2green', ', ', 'default')
[100, 100, 100, 100.0]
('white_to_green', ', ', 'default')
[100, 100, 100, 100.0]
('white2magenta', ', ', 'default')
[100, 100, 100, 100.0]
('white_to_magenta', ', ', 'default')
[100, 100, 100, 100.0]
('blue2grey', ', ', 'default')
[100, 100, 100, 100.0]
('blue_to_grey', ', ', 'default')
[100, 100, 100, 100.0]
('green2magenta', ', ', 'default')
[100, 100, 100, 100.0]
('grn_to_magenta', ', ', 'default')
[100, 100, 100, 100.0]
('white2yellow', ', ', 'default')
[100, 100, 100, 100.0]
('white_to_yellow', ', ', 'default')
[100, 100, 100, 100.0]
('lightblue2darkblue', ', ', 'default')
[100, 100, 100, 100.0]
('ltbl_to_drkbl', ', ', 'default')
[100, 100, 100, 100.0]
('blends', ', ', 'default')
[100, 100, 100, 100.0]
('blue2darkorange', ', ', 'default')
[100, 100, 100, 100.0]
('bl_to_drkorang', ', ', 'default')
[100, 100, 100, 100.0]
('brown2blue', ', ', 'default')
[100, 100, 100, 100.0]
('brown_to_blue', ', ', 'default')
[100, 100, 100, 100.0]
('blue2orange', ', ', 'default')
[100, 100, 100, 100.0]
('blue_to_orange', ', ', 'default')
[100, 100, 100, 100.0]
('AMIP', ', ', 'default')
[100, 100, 100, 100.0]
[100, 100, 100, 100.0]

**Comment by danlipsa** [comment]
Here is the init sequence for Unix
('default', ', ', 'default')
('blue2darkred', ', ', 'default')
('bl_to_darkred', ', ', 'default')
('classic', ', ', 'default')
('viridis', ', ', 'default')
('white2blue', ', ', 'default')
('white_to_blue', ', ', 'default')
('rainbownogreen', ', ', 'default')
('rainbow_no_grn', ', ', 'default')
('magma', ', ', 'default')
('rainbow', ', ', 'default')
[84, 88, 9, 100]
('blue2orange2red', ', ', 'default')
[100, 100, 100, 100.0]
('blue_to_orgred', ', ', 'default')
[100, 100, 100, 100.0]
('categorical', ', ', 'default')
[100, 100, 100, 100.0]
('sequential', ', ', 'default')
[100, 100, 100, 100.0]
('blue2green', ', ', 'default')
[100, 100, 100, 100.0]
('blue_to_grn', ', ', 'default')
[100, 100, 100, 100.0]
('NCAR', ', ', 'default')
[100, 100, 100, 100.0]
('inferno', ', ', 'default')
[100, 100, 100, 100.0]
('plasma', ', ', 'default')
[100, 100, 100, 100.0]
('white2red', ', ', 'default')
[100, 100, 100, 100.0]
('white_to_red', ', ', 'default')
[100, 100, 100, 100.0]
('white2green', ', ', 'default')
[100, 100, 100, 100.0]
('white_to_green', ', ', 'default')
[100, 100, 100, 100.0]
('white2magenta', ', ', 'default')
[100, 100, 100, 100.0]
('white_to_magenta', ', ', 'default')
[100, 100, 100, 100.0]
('blue2grey', ', ', 'default')
[100, 100, 100, 100.0]
('blue_to_grey', ', ', 'default')
[100, 100, 100, 100.0]
('green2magenta', ', ', 'default')
[100, 100, 100, 100.0]
('grn_to_magenta', ', ', 'default')
[100, 100, 100, 100.0]
('white2yellow', ', ', 'default')
[100, 100, 100, 100.0]
('white_to_yellow', ', ', 'default')
[100, 100, 100, 100.0]
('lightblue2darkblue', ', ', 'default')
[100, 100, 100, 100.0]
('ltbl_to_drkbl', ', ', 'default')
[100, 100, 100, 100.0]
('blends', ', ', 'default')
[100, 100, 100, 100.0]
('blue2darkorange', ', ', 'default')
[100, 100, 100, 100.0]
('bl_to_drkorang', ', ', 'default')
[100, 100, 100, 100.0]
('brown2blue', ', ', 'default')
[100, 100, 100, 100.0]
('brown_to_blue', ', ', 'default')
[100, 100, 100, 100.0]
('blue2orange', ', ', 'default')
[100, 100, 100, 100.0]
('blue_to_orange', ', ', 'default')
[100, 100, 100, 100.0]
('AMIP', ', ', 'default')
[100, 100, 100, 100.0]
('rainbow', ', ', 'default')
[84, 88, 9, 100]
('AMIP', ', ', 'default')
[84, 88, 9, 100]
('NCAR', ', ', 'default')
[84, 88, 9, 100]
('blends', ', ', 'default')
[84, 88, 9, 100]
('white_to_blue', ', ', 'default')
[84, 88, 9, 100]
('white_to_green', ', ', 'default')
[84, 88, 9, 100]
('white_to_magenta', ', ', 'default')
[84, 88, 9, 100]
('white_to_red', ', ', 'default')
[84, 88, 9, 100]
('white_to_yellow', ', ', 'default')
[84, 88, 9, 100]
('grn_to_magenta', ', ', 'default')
[84, 88, 9, 100]
('bl_to_darkred', ', ', 'default')
[84, 88, 9, 100]
('bl_to_drkorang', ', ', 'default')
[84, 88, 9, 100]
('blue_to_grn', ', ', 'default')
[84, 88, 9, 100]
('brown_to_blue', ', ', 'default')
[84, 88, 9, 100]
('blue_to_grey', ', ', 'default')
[84, 88, 9, 100]
('blue_to_orange', ', ', 'default')
[84, 88, 9, 100]
('blue_to_orgred', ', ', 'default')
[84, 88, 9, 100]
('rainbow_no_grn', ', ', 'default')
[84, 88, 9, 100]
('ltbl_to_drkbl', ', ', 'default')
[84, 88, 9, 100]
('categorical', ', ', 'default')
[84, 88, 9, 100]
('sequential', ', ', 'default')
[84, 88, 9, 100]

**Comment by doutriaux1** [comment]
is it possible it get overwritten from your ${HOME}.uvcdat directory? Try to remove it.

**Comment by danlipsa** [comment]
@doutriaux1 Good guess. Thats it. Thanks!
