### ISSUE TITLE
Taylor Diagram with EzTemplate

### ISSUE THREAD

**Issue by lee1043** [UV-CDAT/vcs#272]
When plotting Taylor Diagram in EzTemplate, TD does not have proper border lines. 

```python
import vcs
import MV2
import EzTemplate

# Create dummy 7 data
corr = [.2, .5, .7, .85, .9, .95, .99]
std = [1.6, 1.7, 1.5, 1.2 , .8, .9, .98]
data = MV2.array(zip(std, corr))
data.id = "My Taylor Diagram Data"

print 'data:\n', data
print 'data shape:', data.shape

# Set up canvas and template
canvas = vcs.init()
my_template = vcs.createtemplate()
M = EzTemplate.Multi(template=my_template, rows=2,columns=2, x=canvas)
taylor = vcs.createtaylordiagram()

# Loop for sub panels
for i in range(4):
  if i==0:
    r=0
    c=0
  elif i==1:
    r=0
    c=1
  elif i==2:
    r=1
    c=0
  else:
    r=1
    c=1

  t = M.get(legend='local',row = r, column = c)
  taylor.referencevalue = 1.
  canvas.plot(data, t, taylor, skill=taylor.defaultSkillFunction)

# Save image
canvas.png('test.png')
```

![test](https://user-images.githubusercontent.com/17091564/32802496-1110ddf0-c935-11e7-9114-9c73e774bdb0.png)

Boundary lines are showing as rectangular rather than it supposed to be. The ```taylor.referencevalue = 1.``` is not working neither.

**Comment by doutriaux1** [comment]
@lee1043 I think the taylor diagrams need a special template in order to work, (it's using some special atrributes of the template), try to start with
```python
my_template = vcs.createtemplate(source="deftaylor")
```

**Comment by lee1043** [comment]
Awesome, works as expected! Thanks @doutriaux1 

![test](https://user-images.githubusercontent.com/17091564/32806152-6d913e70-c940-11e7-9f6d-2534e2ac2fb7.png)
