### ISSUE TITLE
Idea for canvas reinitialization: x.reinit()

### ISSUE THREAD

**Issue by lee1043** [UV-CDAT/vcs#275]
Currently `removeobject` works for removing individual object or template, but I was thinking something like below, so everything can be easily removed but keep canvas alive so it can be re-used. 

```python
x=vcs.init()
x.plot(d)
x.reinit() ## Clear every objects in the canvas, remaining canvas alive
```

This would help when creating thousands of plots as @durack1 , @gleckler1 and I do, but memory usage is keep increasing because of user missed erase some of vcs object. @doutriaux1 What do you think?

**Comment by doutriaux1** [comment]
@lee1043 I will add a function `vcs.reset()` that will remove all non displayed elements.

**Comment by durack1** [comment]
@lee1043 @doutriaux1 I think a `vcs.reset()` function would be ideal, I wonder whether having keyword args as an additional expansion to the function would be useful?

**Comment by lee1043** [comment]
@doutriaux1 Great, thanks. May I ask when I expect start using it?

**Comment by doutriaux1** [comment]
you may, but you might not like the answer 😸
