### ISSUE TITLE
EzTemplate in CDAT 3.0 beta?

### ISSUE THREAD

**Issue by lee1043** [UV-CDAT/vcs#321]
@doutriaux1 Does CDAT 3.0 beta include EzTemplate? I cannot `import EzTemplate` with below error message.

```  
File "/export_backup/lee1043/anaconda2/envs/cdat.3.0.beta-2/lib/python2.7/site-packages/EzTemplate/__init__.py", line 2, in <module>
    import vcsaddons.EzTemplate
ImportError: No module named EzTemplate
```

**Comment by doutriaux1** [comment]
oh... I changed something related to this yesterday. Let me check

**Comment by doutriaux1** [comment]
@lee1043 the following works for me:
```
python -c "import vcsaddons; vcsaddons.EzTemplate.Multi(columns=3,rows=4)"
```

**Comment by doutriaux1** [comment]
I'll look into why EzTemplate fails by itself tomorrow.

**Comment by lee1043** [comment]
So it seems like I should import `import vcsaddons` and use `vcsaddons.EzTemplate` rather than `import EzTemplate`, correct?
