### ISSUE TITLE
text alignment seems a bit off

### ISSUE THREAD

**Issue by chaosphere2112** [UV-CDAT/vcs#47]
One would expect the `cross` to be drawn exactly in the center of the middle `H` it is instead a bit off to the left and down

``` python
import vcs
x=vcs.init()
t = vcs.createtext()
t.x=[.8]
t.y=[.8]
t.string = "HHHHH"
t.valign = "half"
t.halign="center"
x.plot(t)
l=vcs.createline()
l.color=["red"]
l.x=[.1,.9]
l.y=[t.y,t.y]
x.plot(l)
l=vcs.createline()
l.color=["blue"]
l.y=[.1,.9]
l.x=[t.x,t.x]
x.plot(l)
x.png("blah")
raw_input("Blah")
```

![blah](https://cloud.githubusercontent.com/assets/2781425/17537385/004adef8-5e51-11e6-8d10-a731f6024955.png)

Migrated from: https://github.com/UV-CDAT/uvcdat/issues/2082

**Comment by danlipsa** [comment]
@aashish24 @doutriaux1 @chaosphere2112 Here are some test files from the latest VTK showing various alignments of labels. I am working to use that VTK into uvcdat.

multiLineText
http://www.vtk.org/files/ExternalData/MD5/63c4f3d5bb1dcfcd0592fa7522316f66

TestScatterPlotMatrixVisible
http://www.vtk.org/files/ExternalData/MD5/fa2c3d87a180352afa623b0be3dff100

**Comment by danlipsa** [comment]
Here is the test run with that VTK;
![blah](https://cloud.githubusercontent.com/assets/6180727/20771724/9e6e16e8-b718-11e6-86ef-7970053bec0c.png)

**Comment by durack1** [comment]
@danlipsa UV-CDAT/uvcdat#1077, UV-CDAT/uvcdat#1079, UV-CDAT/uvcdat#1080 and UV-CDAT/uvcdat#2082 may also provide some user insights/be relevant/duplicates here

**Comment by aashish24** [comment]
@danlipsa the result are looking very good, thanks for the hard-work on tracking this.

**Comment by aashish24** [comment]
@durack1 thanks for tracking the issues. @danlipsa can you have a look at them?

**Comment by danlipsa** [comment]
@durack1 @aashish24 Thanks for tracking these issues. I think there are very nice bits there that we can add to our test suite. Some complain about the text size changing between versions. My latest VTK update resulted in text size change - this was just one pixel difference I think. Big changes should not happen - unless there are bugs that could be fixed.
