### ISSUE TITLE
isofill broken

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/vcs#5]
@danlipsa I think your PR broke vcs

using commit: 507d2bc0c3fd3e8b42974f9ffce34833139ea4bd the uvcmetrics test 04 works, any commit after that I get the wrong colors for an isofill on test 04
```
git clone git://github.com/UV-CDAT/uvcmetrics
cd uvcmetrics
python setup.py install
cmake .
ctest -R 04 -D Experimental
```
leads to bad plots, look for example at: https://open.cdash.org/testDetails.php?test=484915834&build=4560808

Notice that we now have a level that shows values greater than 300 when the max is at: 294.

We fixed a similar issue before: https://github.com/UV-CDAT/uvcdat/issues/1947

PR for fix was : https://github.com/UV-CDAT/uvcdat/pull/2027

This is an URGENT matter for the diags due out this week.

**Comment by doutriaux1** [comment]
@danlipsa also I now get these warnings:

```4: /home/doutriaux1/miniconda2/envs/2016.9.20/bin/diags --outputdir /tmp/doutriaux1/tmpFgXiZq/ --no-antialiasing --model path=/git/uvcmetrics/test/data/cam35_data_smaller,climos=no --obs path=/git/uvcmetrics/test/data/obs,filter=f_startswith('NCEP'),climos=yes --package AMWG --set 4 --var T --seasons ANN
4: Warning: In /export/doutriaux1/anaconda2/conda-bld/work/Common/DataModel/vtkDataSet.cxx, line 476
4: vtkPolyData (0x3372220): Cell array GlobalIds with 1 components, has 1520 tuples but there are only 1411 cells
4: 
4: Warning: In /export/doutriaux1/anaconda2/conda-bld/work/Common/DataModel/vtkDataSet.cxx, line 476
4: vtkPolyData (0x3f11e50): Cell array GlobalIds with 1 components, has 1520 tuples but there are only 1411 cells
4: 
4: Warning: In /export/doutriaux1/anaconda2/conda-bld/work/Common/DataModel/vtkDataSet.cxx, line 476
4: vtkPolyData (0x3381390): Cell array GlobalIds with 1 components, has 1520 tuples but there are only 1411 cells
4: 
4: Warning: In /export/doutriaux1/anaconda2/conda-bld/work/Common/DataModel/vtkDataSet.cxx, line 476
4: vtkPolyData (0x453c810): Cell array GlobalIds with 1 components, has 1520 tuples but there are only 1411 cells
4: 
4: Warning: In /export/doutriaux1/anaconda2/conda-bld/work/Common/DataModel/vtkDataSet.cxx, line 476
4: vtkPolyData (0x36352f0): Cell array GlobalIds with 1 components, has 1008 tuples but there are only 934 cells
4: 
4: Warning: In /export/doutriaux1/anaconda2/conda-bld/work/Common/DataModel/vtkDataSet.cxx, line 476
4: vtkPolyData (0x44e7c60): Cell array GlobalIds with 1 components, has 1008 tuples but there are only 934 cells
4: 
```

**Comment by doutriaux1** [comment]
`git revert -n 5680cc3be6afd00ee7ab06363df7a574a29acd6e`

fixes the issue

**Comment by danlipsa** [comment]
@doutriaux1 I'll take a look. How to you build/install cdat with the split vcs?

**Comment by doutriaux1** [comment]
you can use the uvcdat branch `split_repos`

**Comment by doutriaux1** [comment]
or simply install directly from the vcs repo.

**Comment by doutriaux1** [comment]
don't forget to use: `--old-and-unmanageable` when building vcs

**Comment by danlipsa** [comment]
@doutriaux1 Sounds good. I'll take a look.

**Comment by doutriaux1** [comment]
@danlipsa after reverting your commit i get these failures
https://open.cdash.org/viewTest.php?onlyfailed&buildid=4560938

Shouldn't I get more?

**Comment by danlipsa** [comment]
@doutriaux1 You should not get any failure - assuming I started from a repo with no failures.

**Comment by doutriaux1** [comment]
@danlipsa didn't you add test to check what you fixed in that branch?

**Comment by danlipsa** [comment]
@doutriaux1 Everything I changed was in one commit, including the tests - this is the benefit of using just one commit :smile:

**Comment by doutriaux1** [comment]
https://open.cdash.org/viewTest.php?onlyfailed&buildid=4560986

actually looks like the baselines are more wrong

**Comment by aashish24** [comment]
@danlipsa will look into it as the priority. Looks like the labels are wrong in this test "https://open.cdash.org/testDetails.php?test=484965777&build=4560986". All other tests looks reasonable to me but please post message here if we are mistaken.

**Comment by danlipsa** [comment]
@aashish24 Why do you say the labels are wrong?

**Comment by doutriaux1** [comment]
@danlipsa on the baseline of the test pointed to by @aashish24 the labels are on the right, they should be o the left, no?

**Comment by aashish24** [comment]
@doutriaux1 @danlipsa should we close this now?
