### ISSUE TITLE
canvas.png writes a PNG with labels off if bg=0

### ISSUE THREAD

**Issue by chaosphere2112** [UV-CDAT/vcs#70]
Running this test
[test2.txt](https://github.com/UV-CDAT/uvcdat/files/65625/test2.txt)
produces
![bad](https://cloud.githubusercontent.com/assets/6180727/11874925/0eff8468-a4b0-11e5-959e-5c3d8b778f14.png)
Uncommenting the line that sets bg to 1 fixes the problem.

Migrated from: https://github.com/UV-CDAT/uvcdat/issues/1740

**Comment by danlipsa** [comment]
@chaosphere2112 @durack1 @doutriaux1 This works with vcs SHA f6a88670f89bcbd476c106c6d5695902581ca565 from Apr 5.
